export const THOUSAND_THROTTLE_TIME = 1000;
export const TWO_THOUSAND_THROTTLE_TIME = 2000;
export const  THREE_THOUSAND_THROTTLE_TIME = 3000;
export const  FOUR_THOUSAND_THROTTLE_TIME = 4000;
export const  FIVE_THOUSAND_THROTTLE_TIME = 5000;
export const SIX_THOUSAND_THROTTLE_TIME = 6000;
export const SEVEN_THOUSAND_THROTTLE_TIME = 7000;
export const EIGHT_THOUSAND_THROTTLE_TIME = 8000;
export const NINE_THOUSAND_THROTTLE_TIME = 9000;
export const TEN_THOUSAND_THROTTLE_TIME = 10000;

export const THOUSAND_TIMEOUT_TIME = 1000;
export const TWO_THOUSAND_TIMEOUT_TIME = 2000;
export const THREE_THOUSAND_TIMEOUT_TIME = 3000;
export const FOUR_THOUSAND_TIMEOUT_TIME = 4000;
export const FIVE_THOUSAND_TIMEOUT_TIME = 5000;
export const SIX_THOUSAND_TIMEOUT_TIME = 6000;
export const SEVEN_THOUSAND_TIMEOUT_TIME = 7000;
export const EIGHT_THOUSAND_TIMEOUT_TIME = 8000;
export const NINE_THOUSAND_TIMEOUT_TIME = 9000;
export const TEN_THOUSAND_TIMEOUT_TIME = 10000;

export const DEBOUNCE_2000 = 2000;
export const DEBOUNCE_500 = 500;
export const DEBOUNCE_1000 = 1000;

export const RETRY_COUNT = 3;

export const ERROR_MESSAGE = 'Please try again. Connection error occurred.';

export const DEFAULT_INACTIVITY_DURATION = 15 * 60 * 1000;
